THEME=hugo-theme-cactus-plus

ARTIFACT=pick.bndw.co.tgz
HOST=alaska
DEPLOY_SCRIPT=deploy_pick


all: dev

deploy:
	hugo
	tar -czf $(ARTIFACT) public
	scp $(ARTIFACT) $(HOST):~/
	ssh $(HOST) ./$(DEPLOY_SCRIPT)
	rm $(ARTIFACT)
